INSERT INTO hotel (name, description, price_per_night, location, rating, available_rooms, amenities)
VALUES 
    ('Grand Hotel', 'Luxury hotel in the city center', 299.99, 'Downtown', 4.5, 50, ARRAY['WiFi', 'Pool', 'Spa']),
    ('Seaside Resort', 'Beautiful beachfront property', 399.99, 'Beach Area', 4.8, 75, ARRAY['Beach Access', 'Restaurant', 'Gym']),
    ('Mountain Lodge', 'Cozy mountain retreat', 199.99, 'Mountain View', 4.2, 30, ARRAY['Hiking Trail', 'Restaurant', 'Parking']),
    ('Urban Suites', 'Modern business hotel with conference facilities', 259.99, 'Financial District', 4.3, 100, ARRAY['Business Center', 'WiFi', 'Conference Rooms', 'Restaurant']),
    ('Palm Paradise', 'Tropical resort with private beach', 499.99, 'Coastal Area', 4.9, 45, ARRAY['Private Beach', 'Spa', 'Multiple Pools', 'Water Sports']),
    ('Heritage Inn', 'Historic boutique hotel in old town', 189.99, 'Old Town', 4.4, 25, ARRAY['Antique Furnishings', 'Garden', 'Tea Room']),
    ('Sky Tower Hotel', 'Modern high-rise with city views', 349.99, 'City Center', 4.6, 150, ARRAY['Rooftop Bar', 'Observatory Deck', 'Fine Dining']),
    ('Forest Retreat', 'Secluded nature resort', 279.99, 'Forest Reserve', 4.7, 20, ARRAY['Nature Trails', 'Wildlife Tours', 'Meditation Center']),
    ('Business Elite', 'Premium business accommodations', 289.99, 'Business District', 4.4, 80, ARRAY['Meeting Rooms', 'Executive Lounge', '24/7 Business Center']),
    ('Lakeside Manor', 'Elegant resort by the lake', 359.99, 'Lake District', 4.6, 60, ARRAY['Water Sports', 'Private Dock', 'Fishing']),
    ('Desert Oasis', 'Luxury desert resort and spa', 449.99, 'Desert Region', 4.8, 40, ARRAY['Desert Safari', 'Spa', 'Pool', 'Stargazing Deck']),
    ('Alpine Lodge', 'Ski-in ski-out mountain resort', 399.99, 'Ski Resort', 4.7, 55, ARRAY['Ski Storage', 'Hot Tub', 'Fireplace Lounge']),
    ('City Lights Hotel', 'Contemporary urban hotel', 229.99, 'Downtown', 4.2, 120, ARRAY['City Tours', 'Bike Rental', 'Cafe']),
    ('Riverside Inn', 'Charming waterfront property', 179.99, 'Riverside', 4.3, 35, ARRAY['River Views', 'Fishing Dock', 'BBQ Area']),
    ('Ocean View Resort', 'Luxury oceanfront resort', 549.99, 'Coastal', 4.9, 90, ARRAY['Private Beach', 'Water Sports', 'Multiple Restaurants']),
    ('Historic Plaza Hotel', 'Landmark hotel in city center', 279.99, 'Historic District', 4.5, 70, ARRAY['Heritage Tours', 'Afternoon Tea', 'Ballroom']),
    ('Golf Resort & Spa', 'Premium golf resort', 459.99, 'Golf Estate', 4.7, 65, ARRAY['18-hole Golf Course', 'Pro Shop', 'Tennis Courts']),
    ('Metro Suites', 'All-suite business hotel', 239.99, 'Business Park', 4.3, 85, ARRAY['Kitchenette', 'Work Space', 'Fitness Center']),
    ('Vineyard Estate', 'Wine country luxury resort', 399.99, 'Wine Region', 4.8, 30, ARRAY['Wine Tasting', 'Vineyard Tours', 'Gourmet Restaurant']),
    ('Airport Plaza', 'Convenient airport hotel', 159.99, 'Airport Area', 4.0, 200, ARRAY['Airport Shuttle', '24/7 Service', 'Sound-proof Rooms']),
    ('Wellness Retreat', 'Health and wellness focused resort', 329.99, 'Mountain Valley', 4.6, 40, ARRAY['Yoga Studio', 'Organic Restaurant', 'Meditation Gardens']),
    ('Family Resort', 'Family-friendly vacation resort', 289.99, 'Theme Park District', 4.4, 150, ARRAY['Kids Club', 'Water Park', 'Family Activities']),
    ('Executive Tower', 'Premium business hotel', 309.99, 'Financial Center', 4.5, 100, ARRAY['Executive Lounge', 'Meeting Facilities', 'Helipad']);
